### ISSUE TITLE
Bootstrap v5

### ISSUE THREAD

**Issue by brxck** [uarizona-fnsv/bootstrap#6]
https://getbootstrap.com/docs/5.0/migration/

**Comment by xezian** [comment]
Looking into this, I have a couple of questions:

1. What's the best way to test changes? I can see manually importing the package to an app that relies on it, but is there a better way to make sure all customizations are working right? Is it worth extending the docs (color theme) page to utilize every customized style? I realize there would still be breaking changes that effect the way core bootstrap works in a given app.
2. I see that `docs/index.html` gets it's bootstrap from `"https://assets.cdn.fso.arizona.edu/fso-bootstrap/bootstrap.css"`. What is publishing it there? Can we get it to use the compiled bootstrap from this package itself?

**Comment by brxck** [comment]
First things first, there shouldn't be a lot to do or test here. If you're moving to Bootstrap 5, then I would drop every change except for color scheme. There's no reason to customize any more than that. I've already cut a lot of the customization out of this package.

> What's the best way to test changes?

You probably want [npm-link](https://docs.npmjs.com/cli/v7/commands/npm-link) if you're developing in an app. The customizations left here are pretty minimal/cosmetic though.

> Is it worth extending the docs (color theme) page to utilize every customized style?

I think it's pretty thorough already; again, there should only be color changes.

> I see that docs/index.html gets it's bootstrap from "https://...." What is publishing it there?

It used to be set up in CI before we were using the package registry.

> Can we get it to use the compiled bootstrap from this package itself?

You can't do it directly because the CSS is being built in CI, that's why I was using the package in S3. Unfortunately its not as simple now that the package is in the GPR.

**Comment by brxck** [comment]
I'll also say, migrating existing apps to a newer Bootstrap version should be pretty low impact and thus pretty low priority.
